services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./socialNetwork:/socialNetwork
    environment:
      - DB_HOST=database
      - DB_NAME=socialNetwork_db
      - DB_USER=socialNetwork_user
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=socialNetwork_db
      - POSTGRES_USER=socialNetwork_user
      - POSTGRES_PASSWORD=pass