# Generated by Django 3.2.16 on 2023-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
