# Generated by Django 3.2.16 on 2023-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNApp', '0003_alter_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='SNApp.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
