# Generated by Django 3.2.16 on 2023-09-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNApp', '0004_auto_20230930_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNApp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='likes_post', through='SNApp.UserCommentRelation', to='SNApp.User'),
        ),
    ]
