# Generated by Django 3.2.16 on 2023-10-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNApp', '0005_auto_20230930_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='owner',
        ),
    ]
